[package]
name = "rho-ai-anthropic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
async-stream.workspace = true
base64.workspace = true
futures-util.workspace = true
reqwest.workspace = true
rho-ai.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
webpki-root-certs.workspace = true
