[package]
name = "rho-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
futures-util.workspace = true
rho-ai.workspace = true
rho-core.workspace = true
rho-store.workspace = true
rho-tools.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true
tokio.workspace = true
