[package]
name = "rho-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "rho"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
rho-agent.workspace = true
rho-ai.workspace = true
rho-ai-anthropic.workspace = true
rho-ai-openai.workspace = true
rho-core.workspace = true
rho-rpc.workspace = true
rho-shelterwood.workspace = true
rho-store.workspace = true
rho-tools.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
